/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.farmacia.Presentacion;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import mx.itson.farmacia.Entidades.Doctor;
import mx.itson.farmacia.Entidades.DerechoHabiente;
import mx.itson.farmacia.Implementacion.IDerechoHabiente;
import mx.itson.farmacia.Implementacion.IDoctor;
import mx.itson.farmacia.Interfaz.DerechoHabienteInterfaz;
import mx.itson.farmacia.Interfaz.DoctorInterfaz;

/**
 *
 * @author Laprada
 */
public class DerechoHabienteAgregar extends javax.swing.JInternalFrame {

    /**
     * Creates new form VerDerechoHabiento
     */
    public DerechoHabienteAgregar() {
        initComponents();
        
        
    }

   
    //Interfaces para objetos.
    
    DerechoHabienteInterfaz dhi = new IDerechoHabiente();
    DoctorInterfaz dr = new IDoctor();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombreDh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellidoDh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDomicilioDh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCiudadDh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAfiliacionDh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEdadDh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFechaIngresoDh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbxAsignarDoctorDh = new javax.swing.JComboBox<Doctor>();
        jLabel9 = new javax.swing.JLabel();
        txtDependenciaDh = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnRegistrarDh = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtTelefonoDh = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Derecho Habiente");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Nombre:");

        txtNombreDh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreDhActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Apellido:");

        txtApellidoDh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoDhActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Domicilio:");

        txtDomicilioDh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDomicilioDhActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Ciudad:");

        txtCiudadDh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCiudadDhActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Telefono:");

        txtAfiliacionDh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAfiliacionDhActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Edad:");

        txtEdadDh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadDhActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Fecha de ingreso:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Asignar doctor");

        cbxAsignarDoctorDh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxAsignarDoctorDh.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbxAsignarDoctorDhAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Dependencia:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Dar de alta derechohabiente");

        btnRegistrarDh.setText("Registrar");
        btnRegistrarDh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDhActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Afiliación:");

        txtTelefonoDh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoDhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegistrarDh)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreDh)
                                    .addComponent(txtDomicilioDh)
                                    .addComponent(txtAfiliacionDh, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(txtTelefonoDh, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEdadDh, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellidoDh, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCiudadDh, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxAsignarDoctorDh, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDependenciaDh, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaIngresoDh, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreDh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellidoDh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cbxAsignarDoctorDh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDomicilioDh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtCiudadDh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtDependenciaDh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtEdadDh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaIngresoDh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtTelefonoDh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtAfiliacionDh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnRegistrarDh)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreDhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreDhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDhActionPerformed

    private void txtApellidoDhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoDhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoDhActionPerformed

    private void txtDomicilioDhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDomicilioDhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDomicilioDhActionPerformed

    private void txtCiudadDhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiudadDhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudadDhActionPerformed

    private void txtAfiliacionDhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAfiliacionDhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAfiliacionDhActionPerformed

    private void txtEdadDhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadDhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadDhActionPerformed

    private void btnRegistrarDhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDhActionPerformed
        // TODO add your handling code here:
        
        String nombre = txtNombreDh.getText().trim();
        String apellido = txtApellidoDh.getText().trim();
        String domicilio = txtDomicilioDh.getText().trim();
        String ciudad = txtCiudadDh.getText().trim();
        String telefono = txtTelefonoDh.getText().trim();
        Doctor doctor = (Doctor) cbxAsignarDoctorDh.getSelectedItem();
        int edad = Integer.parseInt(txtEdadDh.getText().trim());
        int afiliacion = Integer.parseInt(txtAfiliacionDh.getText().trim());
        
        String dependencia = txtDependenciaDh.getText().trim();
        String fechaIngreso = txtFechaIngresoDh.getText().trim();
        
        DerechoHabiente dh = new DerechoHabiente( nombre, apellido, domicilio, ciudad, telefono, edad, afiliacion,doctor, dependencia, fechaIngreso);
        if(nombre.isEmpty() || apellido.isEmpty() || domicilio.isEmpty() || ciudad.isEmpty() || telefono.isEmpty() || dependencia.isEmpty() || fechaIngreso.isEmpty()){
           
            JOptionPane.showMessageDialog(null, "No se pueden dejar cajas de texto vacias.");
               
        }else {
            dhi.agregarDerechoHabiente(dh);
            dr.agregarDerechoHabienteLista(dh, doctor);
            
            //Limpiar cajas de texto
            txtNombreDh.setText(null);
            txtApellidoDh.setText(null);
            txtDomicilioDh.setText(null);
            txtCiudadDh.setText(null);
            txtEdadDh.setText(null);
            txtTelefonoDh.setText(null);
            txtAfiliacionDh.setText(null);
        }
       
        
    }//GEN-LAST:event_btnRegistrarDhActionPerformed

    private void cbxAsignarDoctorDhAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbxAsignarDoctorDhAncestorAdded
        // TODO add your handling code here:
      
        
        for(Doctor doctor : dr.mostrarDoctores()){
            cbxAsignarDoctorDh.addItem(doctor);
        }
       
      
    }//GEN-LAST:event_cbxAsignarDoctorDhAncestorAdded

    private void txtTelefonoDhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoDhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoDhActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarDh;
    private javax.swing.JComboBox<Doctor> cbxAsignarDoctorDh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAfiliacionDh;
    private javax.swing.JTextField txtApellidoDh;
    private javax.swing.JTextField txtCiudadDh;
    private javax.swing.JTextField txtDependenciaDh;
    private javax.swing.JTextField txtDomicilioDh;
    private javax.swing.JTextField txtEdadDh;
    private javax.swing.JTextField txtFechaIngresoDh;
    private javax.swing.JTextField txtNombreDh;
    private javax.swing.JTextField txtTelefonoDh;
    // End of variables declaration//GEN-END:variables
}
