/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.farmacia.Presentacion;

import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import mx.itson.farmacia.Implementacion.IValidacion;
import mx.itson.farmacia.Interfaz.ValidacionInterfaz;

/**
 *
 * @author Laprada
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    boolean status = false;
    public Menu() {
        
       
             initComponents();
             jMenuBarFarmacia.setVisible(status);
             
        
       
    }

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Escritorio = new javax.swing.JDesktopPane();
        LoginFrame = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        jMenuBarFarmacia = new javax.swing.JMenuBar();
        btnPanelPrincipal = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuDoctor = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuLaboratorio = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuProducto = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuSalida = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginFrame.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Login");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Contraseña:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Usuario:");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginFrameLayout = new javax.swing.GroupLayout(LoginFrame.getContentPane());
        LoginFrame.getContentPane().setLayout(LoginFrameLayout);
        LoginFrameLayout.setHorizontalGroup(
            LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFrameLayout.createSequentialGroup()
                .addGroup(LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginFrameLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(LoginFrameLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(txtContraseña)))
                    .addGroup(LoginFrameLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btnIngresar)))
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LoginFrameLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jLabel3)
                    .addContainerGap(238, Short.MAX_VALUE)))
        );
        LoginFrameLayout.setVerticalGroup(
            LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnIngresar)
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LoginFrameLayout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(jLabel3)
                    .addContainerGap(176, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(499, 499, 499)
                .addComponent(LoginFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(471, Short.MAX_VALUE))
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(LoginFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        Escritorio.setLayer(LoginFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnPanelPrincipal.setText("Panel Principal");
        btnPanelPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelPrincipalActionPerformed(evt);
            }
        });

        jMenu3.setText("Derecho Habientes");

        jMenuItem11.setText("Registrar");
        jMenuItem11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem11MouseClicked(evt);
            }
        });
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem12.setText("Ver Derecho Habientes");
        jMenuItem12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem12MouseClicked(evt);
            }
        });
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        btnPanelPrincipal.add(jMenu3);

        jMenuUsuario.setText("Usuarios");
        jMenuUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuUsuarioMouseClicked(evt);
            }
        });
        jMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioActionPerformed(evt);
            }
        });

        jMenuItem9.setText("Registrar");
        jMenuItem9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem9MouseClicked(evt);
            }
        });
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItem9);

        jMenuItem10.setText("Ver usuarios");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItem10);

        btnPanelPrincipal.add(jMenuUsuario);

        jMenuDoctor.setText("Doctores");
        jMenuDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuDoctorMouseClicked(evt);
            }
        });
        jMenuDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDoctorActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Registrar Doctor");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuDoctor.add(jMenuItem1);

        jMenuItem2.setText("Ver Doctor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuDoctor.add(jMenuItem2);

        btnPanelPrincipal.add(jMenuDoctor);

        jMenuLaboratorio.setText("Laboratorio");
        jMenuLaboratorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLaboratorioMouseClicked(evt);
            }
        });
        jMenuLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLaboratorioActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Registrar Laboratorio");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuLaboratorio.add(jMenuItem3);

        jMenuItem4.setText("Venta Productos");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseClicked(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuLaboratorio.add(jMenuItem4);

        btnPanelPrincipal.add(jMenuLaboratorio);

        jMenuProducto.setText("Productos");
        jMenuProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuProductoMouseClicked(evt);
            }
        });
        jMenuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProductoActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Registro");
        jMenuItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem5MouseClicked(evt);
            }
        });
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuProducto.add(jMenuItem5);

        jMenuItem6.setText("Venta Productos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuProducto.add(jMenuItem6);

        btnPanelPrincipal.add(jMenuProducto);

        jMenuSalida.setText("Salida");
        jMenuSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSalidaMouseClicked(evt);
            }
        });
        jMenuSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalidaActionPerformed(evt);
            }
        });

        jMenuItem8.setText("Ver Salidas");
        jMenuItem8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem8MouseClicked(evt);
            }
        });
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenuSalida.add(jMenuItem8);

        btnPanelPrincipal.add(jMenuSalida);

        jMenuBarFarmacia.add(btnPanelPrincipal);

        setJMenuBar(jMenuBarFarmacia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPanelPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelPrincipalActionPerformed
       
        
            
        
    }//GEN-LAST:event_btnPanelPrincipalActionPerformed

    private void jMenuDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDoctorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuDoctorActionPerformed

    private void jMenuLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLaboratorioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuLaboratorioActionPerformed

    private void jMenuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProductoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuProductoActionPerformed

    private void jMenuSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalidaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenuSalidaActionPerformed

    private void jMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuUsuarioActionPerformed

    private void jMenuDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuDoctorMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenuDoctorMouseClicked

    private void jMenuLaboratorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLaboratorioMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuLaboratorioMouseClicked

    private void jMenuProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuProductoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuProductoMouseClicked

    private void jMenuSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalidaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuSalidaMouseClicked

    private void jMenuUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuUsuarioMouseClicked
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_jMenuUsuarioMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        DoctorAgregar VentanaDoctor = new DoctorAgregar();
        Escritorio.add(VentanaDoctor);
        VentanaDoctor.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:
        DoctorAgregar VentanaDoctor = new DoctorAgregar();
        Escritorio.add(VentanaDoctor);
        VentanaDoctor.show();
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        VerDoctor VentanaVerDoctor = new VerDoctor();
        Escritorio.add(VentanaVerDoctor);
        VentanaVerDoctor.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        VerLaboratorio VentanaVerLaboratorio = new VerLaboratorio();
        Escritorio.add(VentanaVerLaboratorio);
        VentanaVerLaboratorio.show();
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
        // TODO add your handling code here:
        LaboratorioAgregar VentanaLaboratorio = new LaboratorioAgregar();
        Escritorio.add(VentanaLaboratorio);
        VentanaLaboratorio.show();
    }//GEN-LAST:event_jMenuItem3MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        LaboratorioAgregar VentanaLaboratorio = new LaboratorioAgregar();
        Escritorio.add(VentanaLaboratorio);
        VentanaLaboratorio.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        ProductoAgregar VentanaProducto = new ProductoAgregar();
        Escritorio.add(VentanaProducto);
        VentanaProducto.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem5MouseClicked
        // TODO add your handling code here:
        ProductoAgregar VentanaProducto = new ProductoAgregar();
        Escritorio.add(VentanaProducto);
        VentanaProducto.show();
    }//GEN-LAST:event_jMenuItem5MouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        VerProducto VentanaVerProducto = new VerProducto();
        Escritorio.add(VentanaVerProducto);
        VentanaVerProducto.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        VerSalidas VentanaVerSalidas = new VerSalidas();
        Escritorio.add(VentanaVerSalidas);
        VentanaVerSalidas.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        UsuarioAgregar VentanaDarDeAltaUsuario = new UsuarioAgregar();
        Escritorio.add(VentanaDarDeAltaUsuario);
        VentanaDarDeAltaUsuario.show();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem9MouseClicked
        // TODO add your handling code here:
        UsuarioAgregar VentanaDarDeAltaUsuario = new UsuarioAgregar();
        Escritorio.add(VentanaDarDeAltaUsuario);
        VentanaDarDeAltaUsuario.show();
    }//GEN-LAST:event_jMenuItem9MouseClicked

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        VerUsuario VentanaVerUsuario = new VerUsuario();
        Escritorio.add(VentanaVerUsuario);
        VentanaVerUsuario.show();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        DerechoHabienteAgregar VentanaDerechoHabiento = new DerechoHabienteAgregar();
        Escritorio.add(VentanaDerechoHabiento);
        VentanaDerechoHabiento.show();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        VerDerechoHabiente VentanaVerDerechoHabiento = new VerDerechoHabiente();
        Escritorio.add(VentanaVerDerechoHabiento);
        VentanaVerDerechoHabiento.show();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem11MouseClicked
        // TODO add your handling code here:
        DerechoHabienteAgregar VentanaDerechoHabiento = new DerechoHabienteAgregar();
        Escritorio.add(VentanaDerechoHabiento);
        VentanaDerechoHabiento.show();
    }//GEN-LAST:event_jMenuItem11MouseClicked

    private void jMenuItem12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem12MouseClicked
        // TODO add your handling code here:
        VerDerechoHabiente VentanaVerDerechoHabiento = new VerDerechoHabiente();
        Escritorio.add(VentanaVerDerechoHabiento);
        VentanaVerDerechoHabiento.show();
    }//GEN-LAST:event_jMenuItem12MouseClicked

    private void jMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseClicked
        // TODO add your handling code here:
        VerLaboratorio VentanaVerLaboratorio = new VerLaboratorio();
        Escritorio.add(VentanaVerLaboratorio);
        VentanaVerLaboratorio.show();
    }//GEN-LAST:event_jMenuItem4MouseClicked

    private void jMenuItem8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem8MouseClicked
        // TODO add your handling code here:
        VerSalidas VentanaVerSalidas = new VerSalidas();
        Escritorio.add(VentanaVerSalidas);
        VentanaVerSalidas.show();
    }//GEN-LAST:event_jMenuItem8MouseClicked

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        
        ValidacionInterfaz via = new IValidacion();
        String usuario = txtUsuario.getText().trim();
        String contraseña = txtContraseña.getText().trim();
        if(via.validarCredenciales(usuario, contraseña)== true){
            jMenuBarFarmacia.setVisible(true);
            LoginFrame.dispose();
        }
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
            
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JInternalFrame LoginFrame;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JMenu btnPanelPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBarFarmacia;
    private javax.swing.JMenu jMenuDoctor;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jMenuLaboratorio;
    private javax.swing.JMenu jMenuProducto;
    private javax.swing.JMenu jMenuSalida;
    private javax.swing.JMenu jMenuUsuario;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
