/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.farmacia.Presentacion;

/**
 *
 * @author Laprada
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    Usuario user = 
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBarFarmacia = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuDerechoHabiente = new javax.swing.JMenu();
        jMenuDoctor = new javax.swing.JMenu();
        jMenuLaboratorio = new javax.swing.JMenu();
        jMenuPersona = new javax.swing.JMenu();
        jMenuProducto = new javax.swing.JMenu();
        jMenuSalida = new javax.swing.JMenu();
        jMenuUsuario = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        jMenu1.setText("Ventana");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuDerechoHabiente.setText("DerechoHabiente");
        jMenuDerechoHabiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuDerechoHabienteMouseClicked(evt);
            }
        });
        jMenuDerechoHabiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDerechoHabienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuDerechoHabiente);

        jMenuDoctor.setText("Doctor");
        jMenuDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuDoctorMouseClicked(evt);
            }
        });
        jMenuDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDoctorActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuDoctor);

        jMenuLaboratorio.setText("Laboratorio");
        jMenuLaboratorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLaboratorioMouseClicked(evt);
            }
        });
        jMenuLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLaboratorioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuLaboratorio);

        jMenuPersona.setText("Persona");
        jMenuPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPersonaMouseClicked(evt);
            }
        });
        jMenuPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPersonaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuPersona);

        jMenuProducto.setText("Producto");
        jMenuProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuProductoMouseClicked(evt);
            }
        });
        jMenuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProductoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuProducto);

        jMenuSalida.setText("Salida");
        jMenuSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSalidaMouseClicked(evt);
            }
        });
        jMenuSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalidaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSalida);

        jMenuUsuario.setText("Usuario");
        jMenuUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuUsuarioMouseClicked(evt);
            }
        });
        jMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioActionPerformed(evt);
            }
        });

        jMenu3.setText("Crear Usuario");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuUsuario.add(jMenu3);

        jMenu4.setText("Ver Usuario");
        jMenuUsuario.add(jMenu4);

        jMenu1.add(jMenuUsuario);

        jMenuBarFarmacia.add(jMenu1);

        setJMenuBar(jMenuBarFarmacia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
       
        
            
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDoctorActionPerformed
        // TODO add your handling code here:
        Doctor VentanaDoctor = new Doctor();
        Escritorio.add(VentanaDoctor);
        VentanaDoctor.show();
    }//GEN-LAST:event_jMenuDoctorActionPerformed

    private void jMenuLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLaboratorioActionPerformed
        // TODO add your handling code here:
        Laboratorio VentanaLab = new Laboratorio();
        Escritorio.add(VentanaLab);
        VentanaLab.show();
    }//GEN-LAST:event_jMenuLaboratorioActionPerformed

    private void jMenuPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPersonaActionPerformed
        // TODO add your handling code here:
        Persona VentanaPersona = new Persona();
        Escritorio.add(VentanaPersona);
        VentanaPersona.show();
    }//GEN-LAST:event_jMenuPersonaActionPerformed

    private void jMenuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProductoActionPerformed
        // TODO add your handling code here:
        Producto VentanaProducto = new Producto();
        Escritorio.add(VentanaProducto);
        VentanaProducto.show();
    }//GEN-LAST:event_jMenuProductoActionPerformed

    private void jMenuSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalidaActionPerformed
        // TODO add your handling code here:
        Salida VentanaSalida = new Salida();
        Escritorio.add(VentanaSalida);
        VentanaSalida.show();
    }//GEN-LAST:event_jMenuSalidaActionPerformed

    private void jMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioActionPerformed
        // TODO add your handling code here:
        DarDeAltaUsuario VentanaUsuario = new DarDeAltaUsuario();
        Escritorio.add(VentanaUsuario);
        VentanaUsuario.show();
    }//GEN-LAST:event_jMenuUsuarioActionPerformed

    private void jMenuDerechoHabienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDerechoHabienteActionPerformed
        // TODO add your handling code here:
        DerechoHabiento VentanaHabiente = new DerechoHabiento();
        Escritorio.add(VentanaHabiente);
        VentanaHabiente.show();
    }//GEN-LAST:event_jMenuDerechoHabienteActionPerformed

    private void jMenuDerechoHabienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuDerechoHabienteMouseClicked
        // TODO add your handling code here:
        DerechoHabiento VentanaHabiente = new DerechoHabiento();
        Escritorio.add(VentanaHabiente);
        VentanaHabiente.show();
    }//GEN-LAST:event_jMenuDerechoHabienteMouseClicked

    private void jMenuDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuDoctorMouseClicked
        // TODO add your handling code here:
        Doctor VentanaDoctor = new Doctor();
        Escritorio.add(VentanaDoctor);
        VentanaDoctor.show();
    }//GEN-LAST:event_jMenuDoctorMouseClicked

    private void jMenuLaboratorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLaboratorioMouseClicked
        // TODO add your handling code here:
        Laboratorio VentanaLaboratorio = new Laboratorio();
        Escritorio.add(VentanaLaboratorio);
        VentanaLaboratorio.show();
    }//GEN-LAST:event_jMenuLaboratorioMouseClicked

    private void jMenuPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPersonaMouseClicked
        // TODO add your handling code here:
        Persona VentanaPersona = new Persona();
        Escritorio.add(VentanaPersona);
        VentanaPersona.show();
    }//GEN-LAST:event_jMenuPersonaMouseClicked

    private void jMenuProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuProductoMouseClicked
        // TODO add your handling code here:
        Producto VentanaProducto = new Producto();
        Escritorio.add(VentanaProducto);
        VentanaProducto.show();
    }//GEN-LAST:event_jMenuProductoMouseClicked

    private void jMenuSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalidaMouseClicked
        // TODO add your handling code here:
        Salida VentanaSalida = new Salida();
        Escritorio.add(VentanaSalida);
        VentanaSalida.show();
    }//GEN-LAST:event_jMenuSalidaMouseClicked

    private void jMenuUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuUsuarioMouseClicked
        // TODO add your handling code here:
        VerUsuario VentanaVerUsuario = new VerUsuario();
        Escritorio.add(VentanaVerUsuario);
        VentanaVerUsuario.show();
        
    }//GEN-LAST:event_jMenuUsuarioMouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        DarDeAltaUsuario VentanaUsuario = new DarDeAltaUsuario();
        Escritorio.add(VentanaUsuario);
        VentanaUsuario.show();
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBarFarmacia;
    private javax.swing.JMenu jMenuDerechoHabiente;
    private javax.swing.JMenu jMenuDoctor;
    private javax.swing.JMenu jMenuLaboratorio;
    private javax.swing.JMenu jMenuPersona;
    private javax.swing.JMenu jMenuProducto;
    private javax.swing.JMenu jMenuSalida;
    private javax.swing.JMenu jMenuUsuario;
    // End of variables declaration//GEN-END:variables
}
