/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.farmacia.Presentacion;

import javax.swing.table.DefaultTableModel;
import mx.itson.farmacia.Entidades.DerechoHabiente;
import mx.itson.farmacia.Entidades.Laboratorio;
import mx.itson.farmacia.Implementacion.IDerechoHabiente;
import mx.itson.farmacia.Interfaz.DerechoHabienteInterfaz;

/**
 *
 * @author Laprada
 */
public class VerDerechoHabiente extends javax.swing.JInternalFrame {

    /**
     * Creates new form DerechoHabiento
     */
    public VerDerechoHabiente() {
        initComponents();
    }

    DerechoHabienteInterfaz dhi = new IDerechoHabiente();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostarDerechoHabientesDh = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBusquedaDh = new javax.swing.JTextField();
        btnBusquedaDh = new javax.swing.JButton();
        btnMostrarDerechoHabientes = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        tblMostarDerechoHabientesDh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Domicilio", "Ciudad", "Telefono", "Edad", "Afiliacion", "Doctro", "Dependencial", "Ingreso"
            }
        ));
        tblMostarDerechoHabientesDh.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblMostarDerechoHabientesDhAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tblMostarDerechoHabientesDh);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Derecho Habientes Registros");

        txtBusquedaDh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaDhActionPerformed(evt);
            }
        });

        btnBusquedaDh.setText("Buscar");
        btnBusquedaDh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaDhActionPerformed(evt);
            }
        });

        btnMostrarDerechoHabientes.setText("Mostrar Datos Derecho Habientes");
        btnMostrarDerechoHabientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDerechoHabientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1176, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBusquedaDh)
                                .addGap(18, 18, 18)
                                .addComponent(txtBusquedaDh, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(152, 152, 152)
                                .addComponent(btnMostrarDerechoHabientes)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusquedaDh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusquedaDh)
                    .addComponent(btnMostrarDerechoHabientes))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llenarTabla(){
         
         DefaultTableModel dtm =  new DefaultTableModel();
         tblMostarDerechoHabientesDh.setModel(dtm);
        
        dtm.addColumn("Nombre");
        dtm.addColumn("Apellido");
        dtm.addColumn("Domicilio");
        dtm.addColumn("Ciudad");
        dtm.addColumn("Telefono");
        dtm.addColumn("Edad");
        dtm.addColumn("Afiliación");
        dtm.addColumn("Doctor");
        dtm.addColumn("Dependencia");
        dtm.addColumn("Fecha de Ingreso");
       
        
        for(DerechoHabiente dh: dhi.mostrarDerechoHabientes()){
            
            Object[] fila = new Object[11];
            fila[0] = dh.getNombre();
            fila[1] = dh.getApellido();
            fila[2] = dh.getDomicilio();
            fila[3] = dh.getCiudad();
            fila[4] = dh.getTelefono();
            fila[5] = dh.getEdad();
            fila[6] = dh.getAfiliacion();
            fila[7] = dh.getDoctor();
            fila[8] = dh.getDependencia();
            fila[9] = dh.getFechaIngreso();
           
            
            dtm.addRow(fila);
         
        }
    }
    private void txtBusquedaDhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaDhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaDhActionPerformed

    private void llenarTablaBusqueda(String nombre){
         
         DefaultTableModel dtm =  new DefaultTableModel();
         tblMostarDerechoHabientesDh.setModel(dtm);
        
        dtm.addColumn("Nombre");
        dtm.addColumn("Apellido");
        dtm.addColumn("Domicilio");
        dtm.addColumn("Ciudad");
        dtm.addColumn("Telefono");
        dtm.addColumn("Edad");
        dtm.addColumn("Afiliación");
        dtm.addColumn("Doctor");
        dtm.addColumn("Dependencia");
        dtm.addColumn("Fecha de Ingreso");
       
        
        for(DerechoHabiente dh: dhi.buscarDerechoHabiente(nombre)){
            
             
            Object[] fila = new Object[11];
            fila[0] = dh.getNombre();
            fila[1] = dh.getApellido();
            fila[2] = dh.getDomicilio();
            fila[3] = dh.getCiudad();
            fila[4] = dh.getTelefono();
            fila[5] = dh.getEdad();
            fila[6] = dh.getAfiliacion();
            fila[7] = dh.getDoctor();
            fila[8] = dh.getDependencia();
            fila[9] = dh.getFechaIngreso();
           
            dtm.addRow(fila);
         
        }
    }
    /**
     * Método para mostrar los derecho habientes registrados en el sistema.
     * @param evt 
     */
    private void tblMostarDerechoHabientesDhAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblMostarDerechoHabientesDhAncestorAdded
        // TODO add your handling code here:
        
             llenarTabla();
    }//GEN-LAST:event_tblMostarDerechoHabientesDhAncestorAdded

    private void btnBusquedaDhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaDhActionPerformed
        // TODO add your handling code here:
        String busqueda = txtBusquedaDh.getText().trim();
        llenarTablaBusqueda(busqueda);
    }//GEN-LAST:event_btnBusquedaDhActionPerformed

    private void btnMostrarDerechoHabientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDerechoHabientesActionPerformed
        // TODO add your handling code here:
        
        llenarTabla();
    }//GEN-LAST:event_btnMostrarDerechoHabientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusquedaDh;
    private javax.swing.JButton btnMostrarDerechoHabientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMostarDerechoHabientesDh;
    private javax.swing.JTextField txtBusquedaDh;
    // End of variables declaration//GEN-END:variables
}
