/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.farmacia.Presentacion;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import mx.itson.farmacia.Entidades.Laboratorio;
import mx.itson.farmacia.Entidades.Producto;
import mx.itson.farmacia.Implementacion.ILaboratorio;
import mx.itson.farmacia.Interfaz.LaboratorioInterfaz;

/**
 *
 * @author Laprada
 */
public class VerLaboratorio extends javax.swing.JInternalFrame {

    /**
     * Creates new form VerLaboratorio
     */
    public VerLaboratorio() {
        initComponents();
    }

    LaboratorioInterfaz li = new ILaboratorio();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostrarLaboratorios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBusquedaLab = new javax.swing.JTextField();
        btnBusquedaLab = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLaboratorioProductos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setClosable(true);

        tblMostrarLaboratorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Domicilio", "Ciudad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMostrarLaboratorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMostrarLaboratoriosMouseClicked(evt);
            }
        });
        tblMostrarLaboratorios.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblMostrarLaboratoriosAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tblMostrarLaboratorios);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Productos Registrados por Laboratorio");

        txtBusquedaLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaLabActionPerformed(evt);
            }
        });

        btnBusquedaLab.setText("Busqueda");
        btnBusquedaLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaLabActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Laboratorios");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Productos por Laboratorio");

        tblLaboratorioProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Producto", "Nombre", "Descripcion", "Cantidad", "Precio Unitario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblLaboratorioProductos);

        jLabel4.setText("Nota: La busqueda debe ser por nombre de Lab");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBusquedaLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBusquedaLab, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3))
                .addContainerGap(550, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusquedaLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusquedaLab)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llenarTablaProductos(Laboratorio x){
        DefaultTableModel dtm =  new DefaultTableModel();
        tblLaboratorioProductos.setModel(dtm);
        
        dtm.addColumn("Id Producto");
        dtm.addColumn("Nombre");
        dtm.addColumn("Descripcion");
        dtm.addColumn("Cantidad");
        dtm.addColumn("Precio Unitario");
       
        
        for(Producto y: x.getLista()){
            
            Object[] fila = new Object[6];
            fila[0] = y.getId();
            fila[1] = y.getNombre();
            fila[2] = y.getDescripcion();
            fila[3] = y.getCantidad();
            fila[4] = y.getPrecioUnitario();
            
            dtm.addRow(fila);
         
        }
    }
    private void llenarTablaLaboratorios(String nombre){
         
         DefaultTableModel dtm =  new DefaultTableModel();
         tblMostrarLaboratorios.setModel(dtm);
        
        dtm.addColumn("Id");
        dtm.addColumn("Nombre");
        dtm.addColumn("Domicilio");
        dtm.addColumn("Ciudad");
       
        
        for(Laboratorio lab: li.buscarLaboratorio(nombre)){
            
            Object[] fila = new Object[5];
            fila[0] = lab.getId();
            fila[1] = lab.getNombre();
            fila[2] = lab.getDomicilio();
            fila[3] = lab.getCiudad();
            
            dtm.addRow(fila);
         
        }
    }
     
    private DefaultTableModel llenarTablaLaboratorio(){
         
         DefaultTableModel dtm =  new DefaultTableModel();
         tblMostrarLaboratorios.setModel(dtm);
        
        dtm.addColumn("Id");
        dtm.addColumn("Nombre");
        dtm.addColumn("Domicilio");
        dtm.addColumn("Ciudad");
       
        
        for(Laboratorio lab: li.mostrarLaboratorios()){
            
            Object[] fila = new Object[5];
            fila[0] = lab.getId();
            fila[1] = lab.getNombre();
            fila[2] = lab.getDomicilio();
            fila[3] = lab.getCiudad();
            
            dtm.addRow(fila);
         
        }
        return dtm;
    }
     
    private void llenarTablaLaboratorios(){
         
         DefaultTableModel dtm =  new DefaultTableModel();
         tblMostrarLaboratorios.setModel(dtm);
        
        dtm.addColumn("Id");
        dtm.addColumn("Nombre");
        dtm.addColumn("Domicilio");
        dtm.addColumn("Ciudad");
       
        
        for(Laboratorio lab: li.mostrarLaboratorios()){
            
            Object[] fila = new Object[5];
            fila[0] = lab.getId();
            fila[1] = lab.getNombre();
            fila[2] = lab.getDomicilio();
            fila[3] = lab.getCiudad();
            
            dtm.addRow(fila);
         
        }
    }
    
    private void txtBusquedaLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaLabActionPerformed

    private void btnBusquedaLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaLabActionPerformed
        // TODO add your handling code here:
        String busqueda = txtBusquedaLab.getText().trim();
        llenarTablaLaboratorios(busqueda);
    
        
    }//GEN-LAST:event_btnBusquedaLabActionPerformed

    private void tblMostrarLaboratoriosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblMostrarLaboratoriosAncestorAdded
       
        llenarTablaLaboratorios();
        
    }//GEN-LAST:event_tblMostrarLaboratoriosAncestorAdded

   
    private void tblMostrarLaboratoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMostrarLaboratoriosMouseClicked
        // TODO add your handling code here:
        
        int index = tblMostrarLaboratorios.getSelectedRow();
        int id = Integer.parseInt(llenarTablaLaboratorio().getValueAt(index, 0).toString());
        llenarTablaProductos(li.obtenerLaboratorio(id));
        
        
        
    }//GEN-LAST:event_tblMostrarLaboratoriosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusquedaLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblLaboratorioProductos;
    private javax.swing.JTable tblMostrarLaboratorios;
    private javax.swing.JTextField txtBusquedaLab;
    // End of variables declaration//GEN-END:variables
}
